version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.9
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888;2181
    volumes:
      - zookeeper_data:/data
      - zookeeper_logs:/datalog
    networks:
      - solr-net

  solr1:
    image: solr:9.5
    container_name: solr1
    ports:
      - "8983:8983"
    environment:
      - ZK_HOST=zookeeper:2181
      - SOLR_JAVA_MEM=-Xms512m -Xmx512m
    volumes:
      - solr1_data:/var/solr
    depends_on:
      - zookeeper
    networks:
      - solr-net
    command: 
      - solr-foreground
      - -c  # Run in cloud mode

  solr2:
    image: solr:9.5
    container_name: solr2
    ports:
      - "8984:8983"
    environment:
      - ZK_HOST=zookeeper:2181
      - SOLR_JAVA_MEM=-Xms512m -Xmx512m
    volumes:
      - solr2_data:/var/solr
    depends_on:
      - zookeeper
      - solr1
    networks:
      - solr-net
    command: 
      - solr-foreground
      - -c  # Run in cloud mode

  # Initializer service to set up Solr collections (runs once and exits)
  solr-init:
    image: solr:9.5
    container_name: solr-init
    depends_on:
      - solr1
      - solr2
    networks:
      - solr-net
    environment:
      - ZK_HOST=zookeeper:2181
      - SOLR_HOST=solr1
      - SOLR_PORT=8983
    volumes:
      - ./solr_config:/config
    command: >
      bash -c "
        # Wait for Solr to be available
        echo 'Waiting for Solr to be available...'
        until wget -q --spider http://solr1:8983/solr; do
          sleep 2
        done
        echo 'Solr is up!'
        
        # Create the documents collection
        echo 'Creating documents collection...'
        solr zk upconfig -n documents_config -d /config/documents -z zookeeper:2181
        curl -s 'http://solr1:8983/solr/admin/collections?action=CREATE&name=documents&numShards=2&replicationFactor=2&collection.configName=documents_config'
        
        # Create the vectors collection
        echo 'Creating vectors collection...'
        solr zk upconfig -n vectors_config -d /config/vectors -z zookeeper:2181
        curl -s 'http://solr1:8983/solr/admin/collections?action=CREATE&name=vectors&numShards=2&replicationFactor=2&collection.configName=vectors_config'
        
        echo 'Initialization complete!'
      "

  # Ollama for embeddings
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - solr-net
    # Pull the nomic-embed-text model on startup
    command: >
      sh -c "ollama serve &
             sleep 10 &&
             ollama pull nomic-embed-text &&
             tail -f /dev/null"

  # MCP Server
  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mcp-server
    ports:
      - "8000:8000"
    environment:
      - SOLR_MCP_ZK_HOSTS=zookeeper:2181
      - SOLR_MCP_SOLR_URL=http://solr1:8983/solr
      - SOLR_MCP_DEFAULT_COLLECTION=vectors
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - solr1
      - solr2
      - solr-init
      - ollama
    networks:
      - solr-net
    volumes:
      - ./:/app

networks:
  solr-net:
    driver: bridge

volumes:
  zookeeper_data:
  zookeeper_logs:
  solr1_data:
  solr2_data:
  ollama_data: